# Generated by Django 3.2 on 2021-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_options_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='room_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
